server:
  port: 8080

endpoints:
  restart:
    enabled: true

spring:
  profiles:
    active: dev
  cloud:
    kubernetes:
      config:
        enabled: true
        enableApi: true
      reload:
        enabled: true
        strategy: restart_context
        mode: event
      discovery:
        enabled: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    exchange: foo
    routingkey: foobar

foo:
  config:
    default: "config:foo.config.default, src:application.yml"
    profile: "config:foo.config.profile, src:application.yml"
    mount: "config:foo.config.mount, src:application.yml"
    reload: "config:foo.config.reload, src:application.yml"
    secret: "config:foo.config.secret, src:application.yml"

management.endpoint.restart.enabled: true