server:
  port: 8080

spring:
  profiles:
    active: dev
  cloud:
    kubernetes:
      config:
        enabled: true
        name: foo-service-dynamic
        enableApi: true
      reload:
        enabled: true
        strategy: refresh
        mode: event
      discovery:
        enabled: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    exchange: foo
    routingkey: foobar

foo:
  config:
    default: default
    secret: secret
    configmap: default
    dynamicConfigMap: default