spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  cloud:
    kubernetes:
      config:
        enabled: true
        enableApi: true
      reload:
        enabled: true
        strategy: restart_context
        mode: event
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: secret-rabbit
    exchange: test-exchange
    routingkey: test
  datasource:
    url: jdbc:postgresql://${POSTGRES_DATABASE}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  liquibase:
    change-log: classpath:db/db.changelog.xml
---
spring:
  profiles: test
  liquibase:
    change-log: classpath:db/db.changelog.xml
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: secret-rabbit
    exchange: test-exchange
    routingkey: test