server:
  port: 8080

spring:
  profiles:
    active: dev
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    exchange: foo
    routingkey: foobar

foo:
  config:
    default: default
    secret: secret

