server:
  port: 8080

endpoints:
  restart:
    enabled: true

spring:
  profiles:
    active: dev
  cloud:
    kubernetes:
      config:
        enabled: true
        enableApi: true
      reload:
        enabled: true
        strategy: restart_context
        mode: event
      discovery:
        enabled: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    exchange: foo
    routingkey: foobar

foo:
  config:
    default: default
    secret: secret
    configmap: default
    dynamicConfigMap: default

management.endpoint.restart.enabled: true