server:
  port: 8080

spring:
  profiles:
    active: dev
  cloud:
    kubernetes:
      config:
        enabled: true
        name: foo-service
        enableApi: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    exchange: foo
    routingkey: foobar

foo:
  config:
    default: default
    secret: secret
    dinamicConfigMap: default